name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: Swatinem/rust-cache@v2
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm build
      - run: pnpm tsc
      - run: pnpm test
